name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run Tests (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{github.workspace}}/build
        run: ./tests

      - name: Test CLI apps (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{github.workspace}}/build
        run: ./SquareRootCalc 2 && ./FactorialCalc 4

      - name: Run Tests (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}/build
        run: .\${{env.BUILD_TYPE}}\tests.exe

      - name: Test CLI apps (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}/build
        run: .\${{env.BUILD_TYPE}}\SquareRootCalc.exe 2 && .\${{env.BUILD_TYPE}}\FactorialCalc.exe 4
